import { addTemplate, addTypeTemplate, defineNuxtModule } from "@nuxt/kit";
import { createRequire } from "node:module";

// Generates the #build/icon-metadata template from the installed
// @iconify-json packages, so the icon list is always in sync with the
// dependencies — nothing committed, no manual step. Rebuilt on every
// nuxt dev / nuxt build.
const require = createRequire(import.meta.url);

// FA's fine-grained categories collapsed into the picker's coarser ones.
const CATEGORY_BUCKETS: Record<string, string> = {
  Code: "Development", Editors: "Development", Files: "Development",
  Energy: "Infrastructure", Security: "Infrastructure",
  Computers: "Devices",
  Construction: "Tools",
  Business: "Business", Currency: "Business", Finance: "Business",
  Logistics: "Business", Marketing: "Business", Moving: "Business",
  "Payments & Shopping": "Business", Shopping: "Business",
  Accessibility: "UI", Alert: "UI", Arrows: "UI", "Date & Time": "UI",
  Design: "UI", Emoji: "UI", Hands: "UI", Images: "UI", Interfaces: "UI",
  Mathematics: "UI", Shapes: "UI", Spinners: "UI", Status: "UI",
  Toggle: "UI", Writing: "UI",
  Charity: "Social", Chat: "Social", Communication: "Social",
  Genders: "Social", Political: "Social", Religion: "Social",
  Social: "Social", "Users & People": "Social",
  Buildings: "Business",
  Childhood: "Education", Education: "Education",
  Fitness: "Health", Health: "Health", Medical: "Health", Pharmacy: "Health",
  Animals: "Lifestyle", Clothing: "Lifestyle", Household: "Lifestyle",
  Objects: "Lifestyle", Sports: "Lifestyle",
  Beverage: "Food & Drink", Food: "Food & Drink",
  "Fruits & Vegetables": "Food & Drink",
  "Audio & Video": "Entertainment", Chess: "Entertainment",
  Games: "Entertainment", Music: "Entertainment",
  "Tabletop Gaming": "Entertainment",
  Automotive: "Travel", Camping: "Travel", Hotel: "Travel",
  Maritime: "Travel", Maps: "Travel", Travel: "Travel", Vehicles: "Travel",
  Science: "Science", "Science Fiction": "Science",
  Autumn: "Seasons & Weather", Halloween: "Seasons & Weather",
  Holiday: "Seasons & Weather", Spring: "Seasons & Weather",
  Summer: "Seasons & Weather", Weather: "Seasons & Weather",
  Winter: "Seasons & Weather",
};

// Generated names are "Fa6-<id>" / "Fab-<id>" — the raw Iconify id after a
// pack prefix, so toIconName() can invert them losslessly (PascalCase is
// ambiguous for ids like "buy-n-large").
const titleCase = (id: string) =>
  id.split("-").map((s) => s.replace(/^[a-z]/, (c) => c.toUpperCase())).join(" ");

function collect(pack: string, prefix: string, bucketOf: (id: string, faCategory: string | null) => string) {
  const data = require(`@iconify-json/${pack}/icons.json`);
  const { categories } = require(`@iconify-json/${pack}/metadata.json`);
  const faCategoryOf = (id: string): string | null =>
    Object.keys(categories ?? {}).find((c: string) => categories[c].includes(id)) ?? null;

  const entry = (id: string, parent?: string) => {
    // Aliases carry no category — inherit the parent icon's.
    const faCategory = faCategoryOf(id) ?? (parent ? faCategoryOf(parent) : null);
    return {
      name: `${prefix}-${id}`,
      displayName: titleCase(id),
      category: bucketOf(id, faCategory),
    };
  };
  return [
    ...Object.keys(data.icons).map((id) => entry(id)),
    ...Object.entries(data.aliases ?? {})
      .filter(([, alias]) => !(alias as { hidden?: boolean }).hidden)
      .map(([id, alias]) => entry(id, (alias as { parent: string }).parent)),
  ];
}

function buildList(): string {
  const solidBucket = (id: string, faCategory: string | null) =>
    (faCategory && CATEGORY_BUCKETS[faCategory]) || "UI";
  const icons = [
    ...collect("fa-solid", "Fa6", solidBucket),
    ...collect("fa-brands", "Fab", () => "Brands"),
  ].sort((a, b) => a.category.localeCompare(b.category) || a.name.localeCompare(b.name));

  return `// Auto-generated by modules/icon-metadata.ts — do not edit.
import type { IconMetadata } from "~/utils/iconMetadata";

export const generatedIcons: IconMetadata[] = [
${icons.map((i) => `  { name: "${i.name}", displayName: "${i.displayName}", category: "${i.category}" },`).join("\n")}
];
`;
}

export default defineNuxtModule({
  meta: { name: "icon-metadata" },
  setup() {
    addTemplate({ filename: "icon-metadata.ts", getContents: buildList });
    // The runtime template is a virtual module — declare its shape for TS.
    addTypeTemplate({
      filename: "types/icon-metadata.d.ts",
      getContents: () => `declare module "#build/icon-metadata" {
  import type { IconMetadata } from "~/utils/iconMetadata";

  export const generatedIcons: IconMetadata[];
}
`,
    });
  },
});
